version: '3'

services:
    test:
        build: .
        environment:
          SECRET_KEY: ${SECRET_KEY}
        command: python manage.py test
        volumes:
            - .:/usr/src/app
    web:
        build: .
        environment:
          SECRET_KEY: ${SECRET_KEY}
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - test
