version: '3'

services:
    migration:
        build: .
        command: python3 manage.py migrate
        volumes:
            - .:/usr/src/app

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - migration
