version: '3'

services:
    migration:
        build: .
        env_file:
            - web-variables.env
        command: python3 manage.py migrate
        volumes:
            - .:/usr/src/app
    test:
        build: .
        env_file:
            - web-variables.env
        command: python3 manage.py test
        volumes:
            - .:/usr/src/app
        depends_on:
            - migration
    web:
        build: .
        env_file:
            - web-variables.env
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - test
