version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
