# nixpacks.toml

[phases.setup]
nixPkgs = ["..."]

[phases.build]
cmds = ['python -m pip install -U pip && python -m pip install -r requirements.txt && python manage.py collectstatic']

[start]
cmd = 'python manage.py migrate && gunicorn project4.wsgi'