# Generated by Django 3.0.7 on 2020-07-13 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
