# Generated by Django 3.0.7 on 2020-07-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200716_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.CharField(default='<p><django.db.models.fields.CharField><p>', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
