# Generated by Django 3.0.7 on 2020-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200718_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.CharField(max_length=2000),
        ),
    ]
