name: Django Tests v2
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
        env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
            pip3 install --user django
            python3 manage.py test
