name: Django Tests
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install Django==3.0.8
        pip3 install -r requirements.txt
        python3 manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
